version: "3.8"
services:
  backend:
    container_name: groupomania-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    env_file: ./.env.development
    ports:
      - 3001:3001
    networks:
      - groupomania
    volumes:
      - ./backend:/app/

  mysqldb:
    container_name: db
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env.development
    #  environment:
    #    - MYSQL_ROOT_PASSWORD=xenocrates
    #    - MYSQL_ROOT_HOST =
    #    - MYSQL_USER=root
    #    - MYSQL_DATABASE=groupomania
    networks:
      - groupomania
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql

  frontend:
    container_name: groupomania-ui
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    networks:
      - groupomania
    env_file: ./.env.development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    stdin_open: true
    tty: true

networks:
  groupomania:
    driver: bridge
